version: 2
registries:
  k9-punsj:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/k9-punsj
    username: x-access-token
    password: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    registries:
      - k9-punsj
    groups:
      spring:
        patterns:
          - "spring*"
          - "org.spring*"
      maven:
        patterns:
          - "*"
        exclude-patterns:
          - "no.nav*"
          - "*k9*"
          - "spring*"
          - "org.spring*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      github:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
