package no.nav.k9punsj.innsending.journalforjson

import org.slf4j.LoggerFactory
import java.util.*

// https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
internal enum class Land(internal val navn: String) {
    ABW("Aruba"),
    AFG("Afghanistan"),
    AGO("Angola"),
    AIA("Anguilla"),
    ALA("Åland"),
    ALB("Albania"),
    AND("Andorra"),
    ARE("De forente arabiske emirater"),
    ARG("Argentina"),
    ARM("Armenia"),
    ASM("Amerikansk Samoa"),
    ATA("Antarktis"),
    ATF("De franske sørterritorier"),
    ATG("Antigua og Barbuda"),
    AUS("Australia"),
    AUT("Østerrike"),
    AZE("Aserbajdsjan"),
    BDI("Burundi"),
    BEL("Belgia"),
    BEN("Benin"),
    BES("Bonaire, Sint Eustatius og Saba"),
    BFA("Burkina Faso"),
    BGD("Bangladesh"),
    BGR("Bulgaria"),
    BHR("Bahrain"),
    BHS("Bahamas"),
    BIH("Bosnia-Hercegovina"),
    BLM("Saint-Barthélemy"),
    BLR("Hviterussland"),
    BLZ("Belize"),
    BMU("Bermuda"),
    BOL("Bolivia"),
    BRA("Brasil"),
    BRB("Barbados"),
    BRN("Brunei"),
    BTN("Bhutan"),
    BVT("Bouvetøya"),
    BWA("Botswana"),
    CAF("Den sentralafrikanske republikk"),
    CAN("Canada"),
    CCK("Kokosøyene"),
    CHE("Sveits"),
    CHL("Chile"),
    CHN("Kina"),
    CIV("Elfenbenskysten"),
    CMR("Kamerun"),
    COD("Den demokratiske republikken Kongo"),
    COG("Republikken Kongo"),
    COK("Cookøyene"),
    COL("Colombia"),
    COM("Komorene"),
    CPV("Kapp Verde"),
    CRI("Costa Rica"),
    CUB("Cuba"),
    CUW("Curaçao"),
    CXR("Christmasøya"),
    CYM("Caymanøyene"),
    CYP("Kypros"),
    CZE("Tsjekkia"),
    DEU("Tyskland"),
    DJI("Djibouti"),
    DMA("Dominica"),
    DNK("Danmark"),
    DOM("Den dominikanske republikk"),
    DZA("Algerie"),
    ECU("Ecuador"),
    EGY("Egypt"),
    ERI("Eritrea"),
    ESH("Vest-Sahara"),
    ESP("Spania"),
    EST("Estland"),
    ETH("Etiopia"),
    FIN("Finland"),
    FJI("Fiji"),
    FLK("Falklandsøyene"),
    FRA("Frankrike"),
    FRO("Færøyene"),
    FSM("Mikronesiaføderasjonen"),
    GAB("Gabon"),
    GBR("Storbritannia"),
    GEO("Georgia"),
    GGY("Guernsey"),
    GHA("Ghana"),
    GIB("Gibraltar"),
    GIN("Guinea"),
    GLP("Guadeloupe"),
    GMB("Gambia"),
    GNB("Guinea-Bissau"),
    GNQ("Ekvatorial-Guinea"),
    GRC("Hellas"),
    GRD("Grenada"),
    GRL("Grønland"),
    GTM("Guatemala"),
    GUF("Fransk Guyana"),
    GUM("Guam"),
    GUY("Guyana"),
    HKG("Hongkong"),
    HMD("Heard- og McDonaldøyene"),
    HND("Honduras"),
    HRV("Kroatia"),
    HTI("Haiti"),
    HUN("Ungarn"),
    IDN("Indonesia"),
    IMN("Man"),
    IND("India"),
    IOT("Det britiske territoriet i Indiahavet"),
    IRL("Irland"),
    IRN("Iran"),
    IRQ("Irak"),
    ISL("Island"),
    ISR("Israel"),
    ITA("Italia"),
    JAM("Jamaica"),
    JEY("Jersey"),
    JPN("Japan"),
    JOR("Jordan"),
    KAZ("Kasakhstan"),
    KEN("Kenya"),
    KGZ("Kirgisistan"),
    KHM("Kambodsja"),
    KIR("Kiribati"),
    KNA("Saint Kitts og Nevis"),
    KOR("Sør-Korea"),
    KWT("Kuwait"),
    LAO("Laos"),
    LBN("Libanon"),
    LBR("Liberia"),
    LBY("Libya"),
    LCA("Saint Lucia"),
    LIE("Liechtenstein"),
    LKA("Sri Lanka"),
    LSO("Lesotho"),
    LTU("Litauen"),
    LUX("Luxembourg"),
    LVA("Latvia"),
    MAC("Macao"),
    MAF("Saint-Martin"),
    MAR("Marokko"),
    MCO("Monaco"),
    MDA("Moldova"),
    MDG("Madagaskar"),
    MDV("Maldivene"),
    MEX("Mexico"),
    MHL("Marshalløyene"),
    MKD("Nord-Makedonia"),
    MLI("Mali"),
    MLT("Malta"),
    MMR("Myanmar"),
    MNE("Montenegro"),
    MNG("Mongolia"),
    MNP("Nord-Marianene"),
    MOZ("Mosambik"),
    MRT("Mauritania"),
    MSR("Montserrat"),
    MTQ("Martinique"),
    MUS("Mauritius"),
    MWI("Malawi"),
    MYS("Malaysia"),
    MYT("Mayotte"),
    NAM("Namibia"),
    NCL("Ny-Caledonia"),
    NER("Niger"),
    NFK("Norfolkøya"),
    NGA("Nigeria"),
    NIC("Nicaragua"),
    NIU("Niue"),
    NLD("Nederland"),
    NOR("Norge"),
    NPL("Nepal"),
    NRU("Nauru"),
    NZL("Ny-Zealand"),
    OMN("Oman"),
    PAK("Pakistan"),
    PAN("Panama"),
    PCN("Pitcairnøyene"),
    PER("Peru"),
    PHL("Filippinene"),
    PLW("Palau"),
    PNG("Papua Ny-Guinea"),
    POL("Polen"),
    PRI("Puerto Rico"),
    PRK("Nord-Korea"),
    PRT("Portugal"),
    PRY("Paraguay"),
    PSE("De palestinske territoriene"),
    PYF("Fransk Polynesia"),
    QAT("Qatar"),
    REU("Réunion"),
    ROU("Romania"),
    RUS("Russland"),
    RWA("Rwanda"),
    SAU("Saudi-Arabia"),
    SDN("Sudan"),
    SEN("Senegal"),
    SGP("Singapore"),
    SGS("Sør-Georgia og Sør-Sandwichøyene"),
    SHN("St. Helena, Ascension og Tristan da Cunha"),
    SJM("Svalbard og Jan Mayen"),
    SLB("Salomonøyene"),
    SLE("Sierra Leone"),
    SLV("El Salvador"),
    SMR("San Marino"),
    SOM("Somalia"),
    SPM("Saint-Pierre og Miquelon"),
    SRB("Serbia"),
    SSD("Sør-Sudan"),
    STP("São Tomé og Príncipe"),
    SUR("Surinam"),
    SVK("Slovakia"),
    SVN("Slovenia"),
    SWE("Sverige"),
    SWZ("Swaziland"),
    SXM("Sint Maarten"),
    SYC("Seychellene"),
    SYR("Syria"),
    TCA("Turks- og Caicosøyene"),
    TCD("Tsjad"),
    TGO("Togo"),
    THA("Thailand"),
    TJK("Tadsjikistan"),
    TKL("Tokelau"),
    TKM("Turkmenistan"),
    TLS("Øst-Timor"),
    TON("Tonga"),
    TTO("Trinidad og Tobago"),
    TUN("Tunisia"),
    TUR("Tyrkia"),
    TUV("Tuvalu"),
    TWN("Taiwan"),
    TZA("Tanzania"),
    UGA("Uganda"),
    UKR("Ukraina"),
    UMI("USAs ytre småøyer"),
    URY("Uruguay"),
    USA("USA"),
    UZB("Usbekistan"),
    VAT("Vatikanstaten"),
    VCT("Saint Vincent og Grenadinene"),
    VEN("Venezuela"),
    VGB("De britiske Jomfruøyer"),
    VIR("De amerikanske Jomfruøyer"),
    VNM("Vietnam"),
    VUT("Vanuatu"),
    WLF("Wallis- og Futunaøyene"),
    WSM("Samoa"),
    YEM("Jemen"),
    ZAF("Sør-Afrika"),
    ZMB("Zambia"),
    ZWE("Zimbabwe");

    internal companion object {
        private val logger = LoggerFactory.getLogger(Land::class.java)
        init {
            val alleLand = Locale.getISOCountries(Locale.IsoCountryCode.PART1_ALPHA3)
            val harMapping = values().map { it.name }
            val manglerMapping = alleLand.minus(harMapping)
            check(manglerMapping.isEmpty()) { "Mangler mapping av landkoder=$manglerMapping" }
            harMapping.minus(alleLand).takeIf { it.isNotEmpty() }?.also { ugyldigeLandkoder ->
                logger.warn("Inneholder mapping av ugyldige landkoder=$ugyldigeLandkoder")
            }
        }
    }
}