CREATE TABLE IF NOT EXISTS PERSON
(
    ID           SERIAL PRIMARY KEY,
    PERSON_ID    UUID      NOT NULL,
    AKTOER_IDENT CHAR(20)  NOT NULL,
    NORSK_IDENT CHAR(11)  NOT NULL,
    SIST_ENDRET  TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX PERSON_UIDX ON PERSON (AKTOER_IDENT, NORSK_IDENT)
