CREATE TABLE IF NOT EXISTS SOKNADER
(
    ID_SOKNAD        SERIAL PRIMARY KEY,
    ID_MAPPE         UUID      NOT NULL,
    ID_PERSON        INTEGER      NOT NULL,
    SIST_ENDRET      TIMESTAMP NOT NULL,
    ID_PERSON_BARN   INTEGER,
    BARN_FODSELSDATO DATE,
    SOKNAD           JSON,
    CONSTRAINT FK_SOKNADER_1
        FOREIGN KEY (ID_PERSON)
            REFERENCES PERSON (ID),
    CONSTRAINT FK_SOKNADER_2
        FOREIGN KEY (ID_PERSON_BARN)
            REFERENCES PERSON (ID)
)
