CREATE TABLE IF NOT EXISTS PERSON
(
    PERSON_ID     UUID PRIMARY KEY,
    AKTOER_IDENT  VARCHAR(20)                            NOT NULL,
    NORSK_IDENT   VARCHAR(11)                            NOT NULL,
    OPPRETTET_AV  VARCHAR(20)  DEFAULT 'PUNSJ'           NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ENDRET_AV     VARCHAR(20),
    ENDRET_TID    TIMESTAMP(3)
);

CREATE UNIQUE INDEX PERSON_UIDX ON PERSON (AKTOER_IDENT, NORSK_IDENT)
