CREATE TABLE IF NOT EXISTS BUNKE
(
    BUNKE_ID      UUID PRIMARY KEY,
    ID_MAPPE      UUID                                   NOT NULL,
    YTELSE_TYPE   VARCHAR(5)                             NOT NULL,
    OPPRETTET_AV  VARCHAR(20)  DEFAULT 'PUNSJ'           NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ENDRET_AV     VARCHAR(20),
    ENDRET_TID    TIMESTAMP(3),
    CONSTRAINT FK_BUNKE_1
        FOREIGN KEY (ID_MAPPE)
            REFERENCES MAPPE (ID)
);
