CREATE TABLE IF NOT EXISTS JOURNALPOST
(
    JOURNALPOST_ID   VARCHAR(100) PRIMARY KEY,
    DATA             JSONB                                  NOT NULL,
    FERDIG_BEHANDLET BOOLEAN      DEFAULT false             NOT NULL,
    OPPRETTET_AV     VARCHAR(20)  DEFAULT 'PUNSJ'           NOT NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ENDRET_AV        VARCHAR(20),
    ENDRET_TID       TIMESTAMP(3)
)
