CREATE TABLE IF NOT EXISTS BREV
(
    BREV_ID        UUID PRIMARY KEY,
    ID_JOURNALPOST VARCHAR(100)                           NOT NULL,
    BREV_TYPE      VARCHAR(20)                            NOT NULL,
    DATA           JSONB,
    OPPRETTET_AV   VARCHAR(20)  DEFAULT 'PUNSJ'           NOT NULL,
    OPPRETTET_TID  TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ENDRET_AV      VARCHAR(20),
    ENDRET_TID     TIMESTAMP(3),
    CONSTRAINT FK_BREV_1
        FOREIGN KEY (ID_JOURNALPOST)
            REFERENCES JOURNALPOST (JOURNALPOST_ID)
)
