apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: k9-punsj-oidc-auth-proxy
  liveness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://k9-punsj.dev.adeo.no
    - https://k9-punsj.dev.intern.nav.no
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/k9-punsj/default
      - mountPath: /var/run/secrets/nais.io/srvk9punsj
        kvPath: /serviceuser/data/dev/srvk9punsj
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/dev
  webproxy: true
  kafka:
    pool: nav-dev
  env:
    - name: SWAGGER_SERVER_BASE_URL
      value: https://k9-punsj.dev.intern.nav.no
    - name: NAIS_STS_TOKEN_ENDPOINT
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/token
    - name: SAF_BASE_URL
      value: https://saf-q1.dev.intern.nav.no
    - name: SAF_HENTE_JOURNALPOST_SCOPES
      value: api://dev-fss.teamdokumenthandtering.saf/.default
    - name: PDL_BASE_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: GOSYS_BASE_URL
      value: https://oppgave.nais.preprod.local
    - name: SAF_HENTE_DOKUMENT_SCOPES
      value: api://dev-fss.teamdokumenthandtering.saf/.default
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: DEFAULTDS_USERNAME
      value: k9-punsj
    - name: DEFAULTDS_PASSWORD
      value: k9-punsj
    - name: DEFAULTDS_VAULT_MOUNTPATH
      value: postgresql/preprod-fss/
    - name: DEFAULTDS_URL
      value: jdbc:postgresql://b27dbvl014.preprod.local:5432/k9-punsj
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.teamabac/application/authorize
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-punsj"
    - name: K9SAK_BASE_URL
      value: https://k9-sak.nais.preprod.local/k9/sak/api
    - name: K9PUNSJBOLLE_BASE_URL
      value: https://k9-punsjbolle.dev.intern.nav.no/api
    - name : K9PUNSJBOLLE_SCOPE
      value: api://dev-gcp.omsorgspenger.k9-punsjbolle/.default
    - name: APP_NAISSTS_aud
      value: "srvk9sak"
    - name: APP_NAISSTS_discovery_url
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: AAREG_BASE_URL
      value: https://modapp-q1.adeo.no/aareg-services/api/v1
    - name: EREG_BASE_URL
      value: https://modapp-q1.adeo.no/ereg/api/v1
    - name: DOKARKIV_BASE_URL
      value: https://dokarkiv-q1.dev.intern.nav.no
    - name: DOKARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default
    - name: NOTAT_ENABLED
      value: "true"
    - name: FERDIGSTILL_GOSYSOPPGAVE_ENABLED
      value: "true"

      # Integrasjoner (Kafka)
      # topic (p:k9-punsj -> c:k9-formidling) for å opprette en dokumentbestilling
    - name: SEND_BREVBESTILLING_TIL_K9_FORMIDLING
      value: "k9saksbehandling.k9-dokumenthendelse-v1"
      # topic (p:k9-punsj -> c:k9-los-api) for å lage oppgaver i k9-los
    - name: SEND_AKSJONSPUNKTHENDELSE_TIL_K9LOS
      value: "privat-k9punsj-aksjonspunkthendelse-v1"
