apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://k9-punsj.dev.adeo.no
    - https://k9-punsj.dev.intern.nav.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/k9-punsj/default
      - mountPath: /var/run/secrets/nais.io/azuread
        kvPath: /azuread/data/dev/creds/k9-punsj
      - mountPath: /var/run/secrets/nais.io/srvk9punsj
        kvPath: /serviceuser/data/dev/srvk9punsj
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/dev
  webproxy: true
  kafka:
    pool: nav-dev
  env:
    - name: SWAGGER_SERVER_BASE_URL
      value: https://k9-punsj.dev.adeo.no
    - name: AZURE_token_endpoint
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
    - name: AZURE_V1_discovery_url
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: AZURE_V2_discovery_url
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: NAIS_STS_TOKEN_ENDPOINT
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/token
    - name: SAF_BASE_URL
      value: https://saf-q1.nais.preprod.local
    - name: SAF_HENTE_JOURNALPOST_SCOPES
      value: c7adbfbb-1b1e-41f6-9b7a-af9627c04998/.default
    - name: PDL_BASE_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: GOSYS_BASE_URL
      value: https://oppgave.nais.preprod.local
    - name: SAF_HENTE_DOKUMENT_SCOPES
      value: c7adbfbb-1b1e-41f6-9b7a-af9627c04998/.default
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: DEFAULTDS_USERNAME
      value: k9-punsj
    - name: DEFAULTDS_PASSWORD
      value: k9-punsj
    - name: DEFAULTDS_VAULT_MOUNTPATH
      value: postgresql/preprod-fss/
    - name: DEFAULTDS_URL
      value: jdbc:postgresql://b27dbvl014.preprod.local:5432/k9-punsj
    - name: ABAC_PDP_ENDPOINT_URL
      value: https://abac-k9.nais.preprod.local/application/authorize
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-punsj"
    - name: K9SAK_BASE_URL
      value: https://k9-sak.nais.preprod.local/k9/sak/api
    - name: K9PUNSJBOLLE_BASE_URL
      value: https://k9-punsjbolle.dev.intern.nav.no/api
