apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj
  namespace: default
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}:{{ tag }}
  port: 8080
  liveness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://k9-punsj.nais.preprod.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/k9-punsj/default
      - mountPath: /var/run/secrets/nais.io/azureadg
        kvPath: /azuread/data/dev/creds/k9-punsj
      - mountPath: /var/run/secrets/nais.io/srvk9punsj
        kvPath: /serviceuser/data/dev/srvk9punsj
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/dev
  webproxy: true
  env:
    - name: SWAGGER_SERVER_BASE_URL
      value: https://k9-punsj.nais.preprod.local
    - name: AZURE_token_endpoint
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
    - name: AZURE_V1_discovery_url
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration
    - name: AZURE_V2_discovery_url
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: SAF_BASE_URL
      value: https://saf-q1.nais.preprod.local
    - name: SAF_HENTE_JOURNALPOST_SCOPES
      value: c7adbfbb-1b1e-41f6-9b7a-af9627c04998/.default
    - name: SAF_HENTE_DOKUMENT_SCOPES
      value: c7adbfbb-1b1e-41f6-9b7a-af9627c04998/.default
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
