apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
        groups:
          # 0000-GA-k9-drift
          - id: "0bc9661c-975c-4adb-86d1-a97172490662"
      singlePageApplication: true
      replyURLs:
        - https://k9-punsj.dev.intern.nav.no/internal/webjars/swagger-ui/oauth2-redirect.html
  accessPolicy:
    inbound:
      rules:
        - application: k9-punsj-frontend
          namespace: k9saksbehandling
          cluster: dev-gcp
        - application: k9-sak
  liveness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: k9-punsj
            envVarPrefix: DB
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
  webproxy: true
  kafka:
    pool: nav-dev
  envFrom:
    - secret: k9-punsj-secrets
  env:
    - name: SWAGGER_SERVER_BASE_URL
      value: https://k9-punsj.dev.intern.nav.no

    # SAF:
    - name: SAF_BASE_URL
      value: https://saf.dev.intern.nav.no
    - name: SAF_HENTE_JOURNALPOST_SCOPES
      value: api://dev-fss.teamdokumenthandtering.saf/.default
    - name: SAF_HENTE_DOKUMENT_SCOPES
      value: api://dev-fss.teamdokumenthandtering.saf/.default

    # Gosys / Oppgave:
    - name: GOSYS_BASE_URL
      value: http://oppgave.oppgavehandtering
    - name: GOSYS_BASE_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave/.default

    # PDL:
    - name: PDL_BASE_URL
      value: https://pdl-api.dev.intern.nav.no/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default

    # Sikkerhet:
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.k9saksbehandling/application/authorize

    # Audit logging
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-punsj"

      # opentelemetry
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=k9-punsj,service.namespace=k9saksbehandling,deployment.environment=q,nais.backend=elastic-apm;grafana-lgtm"

    # Integrasjoner (Rest)
    - name: K9SAK_BASE_URL
      value: https://k9-sak.nais.preprod.local/k9/sak/api
    - name: K9SAK_SCOPE
      value: api://dev-fss.k9saksbehandling.k9-sak/.default
    - name: AAREG_BASE_URL
      value: https://aareg-services.intern.dev.nav.no/api/v2
    - name: AAREG_SCOPE
      value: api://dev-fss.arbeidsforhold.aareg-services-nais/.default
    - name: EREG_BASE_URL
      value: https://ereg-services.intern.dev.nav.no/api/v1
    - name: DOKARKIV_BASE_URL
      value: https://dokarkiv.dev.intern.nav.no
    - name: DOKARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv/.default

    # Integrasjoner (Kafka)
    - name: SEND_AKSJONSPUNKTHENDELSE_TIL_K9LOS
      value: "k9saksbehandling.punsj-aksjonspunkthendelse-v1"
    - name: SEND_BREVBESTILLING_TIL_K9_FORMIDLING
      value: "k9saksbehandling.k9-dokumenthendelse-v1"
    - name: SEND_OPPDATERING_TIL_K9LOS
      value: "k9saksbehandling.k9-punsj-til-los"
    - name: K9_FORDEL_TOPIC
      value: "k9saksbehandling.fordel-journalforing"

    # Div
    - name: SETT_PAA_VENT_TID
      value: "PT1H"

    # Feature toggles
    - name: FERDIGSTILL_GOSYSOPPGAVE_ENABLED
      value: "true"
    - name: KODEVERDI_SOM_STRING
      value: "true"

      # Swagger
    - name: AZURE_LOGIN_URL
      value: "https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0"


