apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: k9-punsj-oidc-auth-proxy
  liveness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 4000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - https://k9-punsj.nais.adeo.no
    - https://k9-punsj.intern.nav.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/k9-punsj/default
      - mountPath: /var/run/secrets/nais.io/srvk9punsj
        kvPath: /serviceuser/data/prod/srvk9punsj
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/prod
  webproxy: true
  kafka:
    pool: nav-prod
  env:
    - name: DEFAULTDS_USERNAME
      value: k9-punsj
    - name: DEFAULTDS_PASSWORD
      value: k9-punsj
    - name: DEFAULTDS_VAULT_MOUNTPATH
      value: postgresql/prod-fss/
    - name: DEFAULTDS_URL
      value: jdbc:postgresql://A01DBVL012.adeo.no:5432/k9-punsj
    - name: SWAGGER_SERVER_BASE_URL
      value: https://k9-punsj.nais.adeo.no
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443

    # SAF:
    - name: SAF_HENTE_JOURNALPOST_SCOPES
      value: api://prod-fss.teamdokumenthandtering.saf/.default
    - name: SAF_HENTE_DOKUMENT_SCOPES
      value: api://prod-fss.teamdokumenthandtering.saf/.default

    # PDL:
    - name: PDL_BASE_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default

    # Sikkerhet:
    - name: NAIS_STS_TOKEN_ENDPOINT
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.teamabac/application/authorize
    - name: APP_NAISSTS_aud
      value: "srvk9sak"
    - name: APP_NAISSTS_discovery_url
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration

    # Audit logging
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-punsj"

      # Integrasjoner (Rest)
    - name: K9SAK_BASE_URL
      value: https://k9-sak.nais.adeo.no/k9/sak/api
    - name: K9PUNSJBOLLE_BASE_URL
      value: https://k9-punsjbolle.intern.nav.no/api
    - name: K9PUNSJBOLLE_SCOPE
      value: api://prod-gcp.omsorgspenger.k9-punsjbolle/.default
    - name: AAREG_BASE_URL
      value: https://modapp.adeo.no/aareg-services/api/v1
    - name: EREG_BASE_URL
      value: https://modapp.adeo.no/ereg/api/v1
    - name: GOSYS_BASE_URL
      value: https://oppgave.nais.adeo.no
    - name: SAF_BASE_URL
      value: https://saf.intern.nav.no
    - name: DOKARKIV_BASE_URL
      value: https://dokarkiv.intern.nav.no
    - name: DOKARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default

      # Integrasjoner (Kafka)
      # topic (p:k9-punsj -> c:k9-los-api) for å lage oppgaver i k9-los
    - name: SEND_BREVBESTILLING_TIL_K9_FORMIDLING
      value: "privat-k9-dokumenthendelse"
      # topic (p:k9-punsj -> c:k9-formidling) for å opprette en dokumentbestilling
    - name: SEND_AKSJONSPUNKTHENDELSE_TIL_K9LOS
      value: "privat-k9punsj-aksjonspunkthendelse-v1"

    - name: NOTAT_ENABLED
      value: "true"
    - name: SAKER_ENABLED
      value: "true"
