apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - 1509dc91-a955-4e72-b64c-2f049e37c0c6 # 0000-GA-k9-drift
      singlePageApplication: true
      replyURLs:
        - https://k9-punsj.intern.nav.no/internal/swagger/oauth2-redirect.html
  accessPolicy:
    inbound:
      rules:
        - application: k9-punsj-oidc-auth-proxy
        - application: k9-sak
        - application: k9-punsj-frontend
          namespace: k9saksbehandling
          cluster: prod-gcp
  liveness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 4000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - https://k9-punsj.nais.adeo.no
    - https://k9-punsj.intern.nav.no
    - https://k9-punsj.prod-fss-pub.nais.io
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/k9-punsj/default
      - mountPath: /var/run/secrets/nais.io/srvk9punsj
        kvPath: /serviceuser/data/prod/srvk9punsj
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/prod
  webproxy: true
  kafka:
    pool: nav-prod
  env:
    - name: DEFAULTDS_USERNAME
      value: k9-punsj
    - name: DEFAULTDS_PASSWORD
      value: k9-punsj
    - name: DEFAULTDS_VAULT_MOUNTPATH
      value: postgresql/prod-fss/
    - name: DEFAULTDS_URL
      value: jdbc:postgresql://A01DBVL012.adeo.no:5432/k9-punsj
    - name: SWAGGER_SERVER_BASE_URL
      value: https://k9-punsj.intern.nav.no

    # SAF:
    - name: SAF_BASE_URL
      value: https://saf.intern.nav.no
    - name: SAF_HENTE_JOURNALPOST_SCOPES
      value: api://prod-fss.teamdokumenthandtering.saf/.default
    - name: SAF_HENTE_DOKUMENT_SCOPES
      value: api://prod-fss.teamdokumenthandtering.saf/.default

    # Gosys / Oppgave:
    - name: GOSYS_BASE_URL
      value: http://oppgave.oppgavehandtering
    - name: GOSYS_BASE_SCOPE
      value: api://prod-fss.oppgavehandtering.oppgave/.default

    # PDL:
    - name: PDL_BASE_URL
      value: https://pdl-api.intern.nav.no/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default

    # Sikkerhet:
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-k9.k9saksbehandling/application/authorize

    # Audit logging
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-punsj"

    # Integrasjoner (Rest)
    - name: K9SAK_BASE_URL
      value: https://k9-sak.nais.adeo.no/k9/sak/api
    - name: K9SAK_SCOPE
      value: api://prod-fss.k9saksbehandling.k9-sak/.default
    - name: AAREG_BASE_URL
      value: https://aareg-services.intern.nav.no/api/v2
    - name: AAREG_SCOPE
      value: api://prod-fss.arbeidsforhold.aareg-services-nais/.default
    - name: EREG_BASE_URL
      value: https://ereg-services.intern.nav.no/api/v1
    - name: DOKARKIV_BASE_URL
      value: https://dokarkiv.intern.nav.no
    - name: DOKARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default

    # Integrasjoner (Kafka)
    - name: K9_RAPID_TOPIC
      value: "omsorgspenger.k9-rapid-v2"
    - name: SEND_AKSJONSPUNKTHENDELSE_TIL_K9LOS
      value: "k9saksbehandling.punsj-aksjonspunkthendelse-v1"
    - name: SEND_BREVBESTILLING_TIL_K9_FORMIDLING
      value: "k9saksbehandling.k9-dokumenthendelse-v1"
    - name: SEND_OPPDATERING_TIL_K9LOS
      value: "k9saksbehandling.k9-punsj-til-los"
    - name: K9_FORDEL_TOPIC
      value: "k9saksbehandling.fordel-journalforing"
    - name: K9_PUNSJBOLLE_TOPIC
      value: "k9saksbehandling.punsjbar-journalpost"

    # Feature toggles
    - name: FERDIGSTILL_GOSYSOPPGAVE_ENABLED
      value: "false"
    - name: KODEVERDI_SOM_STRING
      value: "false"

    # Swagger
    - name: AZURE_LOGIN_URL
      value: "https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/v2.0"
