apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-punsj
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/actuator/info
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 4000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - https://k9-punsj.nais.adeo.no
    - https://k9-punsj.intern.nav.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/k9-punsj/default
      - mountPath: /var/run/secrets/nais.io/azuread
        kvPath: /azuread/data/prod/creds/k9-punsj
      - mountPath: /var/run/secrets/nais.io/srvk9punsj
        kvPath: /serviceuser/data/prod/srvk9punsj
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/prod
  webproxy: true
  kafka:
    pool: nav-prod
  env:
    - name: SWAGGER_SERVER_BASE_URL
      value: https://k9-punsj.nais.adeo.no
    - name: AZURE_token_endpoint
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/oauth2/v2.0/token
    - name: AZURE_V1_discovery_url
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/.well-known/openid-configuration
    - name: AZURE_V2_discovery_url
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
    - name: NAIS_STS_TOKEN_ENDPOINT
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    - name: SAF_BASE_URL
      value: https://saf.nais.adeo.no
    - name: SAF_HENTE_JOURNALPOST_SCOPES
      value: feb9588b-a3d6-4d2f-8809-97284046ae72/.default
    - name: PDL_BASE_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: GOSYS_BASE_URL
      value: https://oppgave.nais.adeo.no
    - name: SAF_HENTE_DOKUMENT_SCOPES
      value: feb9588b-a3d6-4d2f-8809-97284046ae72/.default
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: DEFAULTDS_USERNAME
      value: k9-punsj
    - name: DEFAULTDS_PASSWORD
      value: k9-punsj
    - name: DEFAULTDS_VAULT_MOUNTPATH
      value: postgresql/prod-fss/
    - name: DEFAULTDS_URL
      value: jdbc:postgresql://A01DBVL012.adeo.no:5432/k9-punsj
    - name: ABAC_PDP_ENDPOINT_URL
      value: https://abac-k9.nais.adeo.no/application/authorize
    - name: AUDITLOGGER_ENABLED
      value: "true"
    - name: AUDITLOGGER_VENDOR
      value: "k9"
    - name: AUDITLOGGER_PRODUCT
      value: "k9-punsj"
    - name: K9SAK_BASE_URL
      value: https://k9-sak.nais.adeo.no/k9/sak/api
    - name: K9PUNSJBOLLE_BASE_URL
      value: https://k9-punsjbolle.intern.nav.no/api
    - name: K9PUNSJBOLLE_SCOPE
      value: api://prod-gcp.omsorgspenger.k9-punsjbolle/.default
    - name: APP_NAISSTS_aud
      value: "srvk9sak"
    - name: APP_NAISSTS_discovery_url
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
