CREATE TABLE IF NOT EXISTS AKSJONSPUNKT
(
    AKSJONSPUNKT_ID     UUID PRIMARY KEY,
    AKSJONSPUNKT_KODE   VARCHAR(20)                            NOT NULL,
    ID_JOURNALPOST      VARCHAR(100)                           NOT NULL,
    AKSJONSPUNKT_STATUS VARCHAR(20)                            NOT NULL,
    FRIST_TID           TIMESTAMP(3),
    VENT_AARSAK         VARCHAR(100),
    OPPRETTET_AV        VARCHAR(20)  DEFAULT 'PUNSJ'           NOT NULL,
    OPPRETTET_TID       TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ENDRET_AV           VARCHAR(20),
    ENDRET_TID          TIMESTAMP(3),
    CONSTRAINT FK_SOKNAD_1
        FOREIGN KEY (ID_JOURNALPOST)
            REFERENCES JOURNALPOST (JOURNALPOST_ID)
)
