kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: k9-kafka-manager
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/kafka-manager:2023.12.13-06.32-bd9f953
  port: 8080
  webproxy: true
  ingresses:
    - https://k9-kafka-manager.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 4919ded1-4999-4c63-94f2-408b259dbe33 # k9saksbehandling
  kafka:
    pool: nav-dev
  env:
    - name: APP_CONFIG_JSON
      value: >
        {
          "topics": [
            {
              "name": "k9saksbehandling.punsjbar-journalpost",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "k9saksbehandling.punsj-aksjonspunkthendelse-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "k9saksbehandling.k9-punsj-til-los",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }
