apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: punsjbar-journalpost
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  pool: {{pool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 6
    replication: 3
    retentionBytes: -1
    retentionHours: 672
  acl:
    - team: k9saksbehandling
      application: k9-punsj
      access: read
    - team: omsorgspenger
      application: k9-punsjbolle
      access: write
    {{#if enablekafkamanager}}
    - team: k9saksbehandling
      application: k9-kafka-manager
      access: readwrite
    {{/if}}