apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: punsjbar-journalpost
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  pool: {{pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 6
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 672  # -1 means unlimited
  acl:
    - team: k9saksbehandling
      application: k9-punsj
      access: read
    - team: omsorgspenger
      application: k9-punsjbolle
      access: write