graph LR
topic-punsj-til-formidling{{privat-k9punsj-aksjonspunkthendelse-v1}}
topic-punsj-til-los{{privat-k9-dokumenthendelse}}
onprem-topic-fordel-til-punsj{{onprem:privat-k9-fordel-journalforing-v1}}
aiven-topic-fordel-til-punsj{{aiven:k9saksbehandling.punsjbar-journalpost}}

k9-punsj-frontend --> |punsjer inn papirsoknader| k9-punsj
k9-punsj --> |lagrer, henter, modifiserer soknader, mapper, bunker, journalposter, personer, aksjonspunkt og brev| k9-punsj-db[(k9-punsj-db)]
k9-punsj --> |oppretter/henter fagsaknummer, henter ruting| k9-punsjbolle
k9-punsj --> |henter perioder og inntektsmeldinger | k9-sak
k9-fordel --> |sender punsjbar journalposthendelse| onprem-topic-fordel-til-punsj
k9-punsj .-> |konsumerer punsjbar journalposthendelse| onprem-topic-fordel-til-punsj
k9-fordel --> |sender punsjbar journalposthendelse| aiven-topic-fordel-til-punsj
k9-punsj .-> |konsumerer punsjbar journalposthendelse| aiven-topic-fordel-til-punsj
k9-punsj --> |sender aksjonspunkthendelse| topic-punsj-til-los
k9-los .-> |konsumerer aksjonspunkthendelse| topic-punsj-til-los
k9-punsj --> |sender brevbestilling| topic-punsj-til-formidling
k9-formidling .-> |konsumerer brevbestilling| topic-punsj-til-formidling
k9-punsj --> |sjekker tilganger for saksbehandler| abac-k9
k9-punsj --> |oppretter oppgave| gosys:::notDomain
k9-punsj --> |henter journalpostinfo og dokument | saf:::notDomain
k9-punsj --> |henter ident, barn, og personopplysninger| pdl:::notDomain
k9-punsj --> |henter arbeidsforhold| aareg:::notDomain
k9-punsj --> |henter organisasjonsnavn| ereg:::notDomain
k9-punsj --> |oppdaterer journalpostdata| dokarkiv:::notDomain
k9-punsj --> |henter ident/enhet for innlogget bruker| azure:::notDomain

classDef notDomain fill:#fff;
