name: Build master & deploy to dev-gcp

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - '.github/*.yml'



jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/sif-gha-workflows/.github/workflows/maven-build-app-db.yml@main
    with:
      java-version: 21
      build-image: ${{ github.actor != 'dependabot[bot]' }}
      push-image: ${{ github.ref_name == github.event.repository.default_branch}}
      upload-image: ${{ github.ref_name != github.event.repository.default_branch }}
      db_schema: k9punsj_unit
      pg_version: 16
    secrets: inherit

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
      contents: write
    if: ${{ github.ref_name == github.event.repository.default_branch}}
    needs: [build-app]
    uses: navikt/sif-gha-workflows/.github/workflows/maven-deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      naiserator_file: deploy/dev-gcp.yml
    secrets: inherit

  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
      contents: write
    if: ${{ github.ref_name == github.event.repository.default_branch}}
    needs: [build-app, deploy-dev]
    uses: navikt/sif-gha-workflows/.github/workflows/maven-deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-fss
      naiserator_file: deploy/prod-fss.yml
    secrets: inherit
