name: Deploy manuelt
on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string
        description: 'Image tag to deploy (example 2023.03.10.080433-f821119)'
      cluster:
        required: true
        type: choice
        description: 'The cluster to deployed to (dev-gcp|prod-fss)'
        options:
          - dev-gcp
          - prod-fss

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: write
      id-token: write
    uses: navikt/sif-gha-workflows/.github/workflows/maven-deploy.yml@main
    with:
      gar: true
      image: ${{ inputs.image }}
      cluster: ${{ inputs.cluster }}
      naiserator_file: deploy/${{ inputs.cluster }}.yml
      namespace: k9saksbehandling
    secrets: inherit
