package no.nav.k9punsj.fordel

enum class PunsjInnsendingType(val kode: String) {
    PAPIRSØKNAD("PAPIRSØKNAD"),
    PAPIRETTERSENDELSE("PAPIRETTERSENDELSE"),
    PAPIRINNTEKTSOPPLYSNINGER("PAPIRINNTEKTSOPPLYSNINGER"),
    DIGITAL_ETTERSENDELSE("DIGITAL_ETTERSENDELSE"),
    INNLOGGET_CHAT("INNLOGGET_CHAT"),
    SKRIV_TIL_OSS_SPØRMSÅL("SKRIV_TIL_OSS_SPØRMSÅL"),
    SKRIV_TIL_OSS_SVAR("SRKIV_TIL_OSS_SVAR");
}
